export type MarkdownDisplayMode = 'compact' | 'comfort';

export const MARKDOWN_MODE_VARIABLES: Record<MarkdownDisplayMode, Record<string, string>> = {
    compact: {
        '--markdown-body-line-height': '1.5rem',
        '--markdown-paragraph-spacing': '0.35rem',
        '--markdown-heading-primary-top': '0.75rem',
        '--markdown-heading-primary-bottom': '0.35rem',
        '--markdown-heading-secondary-top': '0.6rem',
        '--markdown-heading-secondary-bottom': '0.3rem',
        '--markdown-list-spacing': '0.45rem',
        '--markdown-list-indent': '1.5rem',
        '--markdown-list-indent-mobile': '1.25rem',
        '--markdown-list-margin-inline': '0.25rem',
        '--markdown-list-item-gap': '0.25rem',
        '--markdown-list-item-padding-desktop': '0.25rem',
        '--markdown-list-item-padding-mobile': '0.125rem',
        '--markdown-blockquote-spacing': '0.6rem',
        '--markdown-blockquote-padding': '0.75rem',
        '--markdown-divider-spacing': '0.85rem',
        '--markdown-table-spacing': '0.9rem',
        '--markdown-heading1-size': 'var(--text-markdown)',
        '--markdown-heading2-size': 'var(--text-markdown)',
        '--markdown-heading3-size': 'var(--text-markdown)',
        '--markdown-heading4-size': 'var(--text-markdown)',
        '--markdown-heading5-size': 'var(--text-markdown)',
        '--markdown-heading6-size': 'var(--text-markdown)',
    },
    comfort: {
        '--markdown-body-line-height': '1.7rem',
        '--markdown-paragraph-spacing': '0.75rem',
        '--markdown-heading-primary-top': '1.35rem',
        '--markdown-heading-primary-bottom': '0.8rem',
        '--markdown-heading-secondary-top': '1rem',
        '--markdown-heading-secondary-bottom': '0.6rem',
        '--markdown-list-spacing': '0.9rem',
        '--markdown-list-indent': '1.9rem',
        '--markdown-list-indent-mobile': '1.5rem',
        '--markdown-list-margin-inline': '0.35rem',
        '--markdown-list-item-gap': '0.5rem',
        '--markdown-list-item-padding-desktop': '0.45rem',
        '--markdown-list-item-padding-mobile': '0.3rem',
        '--markdown-blockquote-spacing': '1.1rem',
        '--markdown-blockquote-padding': '1rem',
        '--markdown-divider-spacing': '1.2rem',
        '--markdown-table-spacing': '1.2rem',
        '--markdown-heading1-size': '1.25rem',
        '--markdown-heading2-size': '1.15rem',
        '--markdown-heading3-size': '1.05rem',
        '--markdown-heading4-size': '1rem',
        '--markdown-heading5-size': '0.95rem',
        '--markdown-heading6-size': '0.9rem',
    },
};
