/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiError {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "data")]
    pub data: Box<Value>,
}

impl ApiError {
    pub fn new(name: Name, data: Value) -> ApiError {
        ApiError {
            name,
            data: Box::new(data),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "APIError")]
    ApiError,
    #[serde(rename = "UnknownError")]
    UnknownError,
    #[serde(other)]
    Other,
}

impl Default for Name {
    fn default() -> Name {
        Self::ApiError
    }
}

