/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessageTime {
    #[serde(rename = "created", default, skip_serializing_if = "Option::is_none")]
    pub created: Option<f64>,
    #[serde(rename = "completed", default, skip_serializing_if = "Option::is_none")]
    pub completed: Option<f64>,
}

impl AssistantMessageTime {
    pub fn new(created: Option<f64>) -> AssistantMessageTime {
        AssistantMessageTime {
            created,
            completed: None,
        }
    }
}
