/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTui : TUI specific settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTui {
    /// TUI scroll speed
    #[serde(rename = "scroll_speed", skip_serializing_if = "Option::is_none")]
    pub scroll_speed: Option<f64>,
    #[serde(rename = "scroll_acceleration", skip_serializing_if = "Option::is_none")]
    pub scroll_acceleration: Option<Box<models::ConfigTuiScrollAcceleration>>,
}

impl ConfigTui {
    /// TUI specific settings
    pub fn new() -> ConfigTui {
        ConfigTui {
            scroll_speed: None,
            scroll_acceleration: None,
        }
    }
}

