/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigProviderValueOptionsTimeout : Timeout in milliseconds for requests to this provider. Default is 300000 (5 minutes). Set to false to disable timeout.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigProviderValueOptionsTimeout {
}

impl ConfigProviderValueOptionsTimeout {
    /// Timeout in milliseconds for requests to this provider. Default is 300000 (5 minutes). Set to false to disable timeout.
    pub fn new() -> ConfigProviderValueOptionsTimeout {
        ConfigProviderValueOptionsTimeout {
        }
    }
}

