/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigProviderValueModelsValueProvider {
    #[serde(rename = "npm")]
    pub npm: String,
}

impl ConfigProviderValueModelsValueProvider {
    pub fn new(npm: String) -> ConfigProviderValueModelsValueProvider {
        ConfigProviderValueModelsValueProvider {
            npm,
        }
    }
}

