/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigProviderValueModelsValueLimit {
    #[serde(rename = "context")]
    pub context: f64,
    #[serde(rename = "output")]
    pub output: f64,
}

impl ConfigProviderValueModelsValueLimit {
    pub fn new(context: f64, output: f64) -> ConfigProviderValueModelsValueLimit {
        ConfigProviderValueModelsValueLimit {
            context,
            output,
        }
    }
}

