/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KeybindsConfig : Custom keybind configurations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeybindsConfig {
    /// Leader key for keybind combinations
    #[serde(rename = "leader", skip_serializing_if = "Option::is_none")]
    pub leader: Option<String>,
    /// Exit the application
    #[serde(rename = "app_exit", skip_serializing_if = "Option::is_none")]
    pub app_exit: Option<String>,
    /// Open external editor
    #[serde(rename = "editor_open", skip_serializing_if = "Option::is_none")]
    pub editor_open: Option<String>,
    /// List available themes
    #[serde(rename = "theme_list", skip_serializing_if = "Option::is_none")]
    pub theme_list: Option<String>,
    /// Toggle sidebar
    #[serde(rename = "sidebar_toggle", skip_serializing_if = "Option::is_none")]
    pub sidebar_toggle: Option<String>,
    /// View status
    #[serde(rename = "status_view", skip_serializing_if = "Option::is_none")]
    pub status_view: Option<String>,
    /// Export session to editor
    #[serde(rename = "session_export", skip_serializing_if = "Option::is_none")]
    pub session_export: Option<String>,
    /// Create a new session
    #[serde(rename = "session_new", skip_serializing_if = "Option::is_none")]
    pub session_new: Option<String>,
    /// List all sessions
    #[serde(rename = "session_list", skip_serializing_if = "Option::is_none")]
    pub session_list: Option<String>,
    /// Show session timeline
    #[serde(rename = "session_timeline", skip_serializing_if = "Option::is_none")]
    pub session_timeline: Option<String>,
    /// Share current session
    #[serde(rename = "session_share", skip_serializing_if = "Option::is_none")]
    pub session_share: Option<String>,
    /// Unshare current session
    #[serde(rename = "session_unshare", skip_serializing_if = "Option::is_none")]
    pub session_unshare: Option<String>,
    /// Interrupt current session
    #[serde(rename = "session_interrupt", skip_serializing_if = "Option::is_none")]
    pub session_interrupt: Option<String>,
    /// Compact the session
    #[serde(rename = "session_compact", skip_serializing_if = "Option::is_none")]
    pub session_compact: Option<String>,
    /// Scroll messages up by one page
    #[serde(rename = "messages_page_up", skip_serializing_if = "Option::is_none")]
    pub messages_page_up: Option<String>,
    /// Scroll messages down by one page
    #[serde(rename = "messages_page_down", skip_serializing_if = "Option::is_none")]
    pub messages_page_down: Option<String>,
    /// Scroll messages up by half page
    #[serde(rename = "messages_half_page_up", skip_serializing_if = "Option::is_none")]
    pub messages_half_page_up: Option<String>,
    /// Scroll messages down by half page
    #[serde(rename = "messages_half_page_down", skip_serializing_if = "Option::is_none")]
    pub messages_half_page_down: Option<String>,
    /// Navigate to first message
    #[serde(rename = "messages_first", skip_serializing_if = "Option::is_none")]
    pub messages_first: Option<String>,
    /// Navigate to last message
    #[serde(rename = "messages_last", skip_serializing_if = "Option::is_none")]
    pub messages_last: Option<String>,
    /// Copy message
    #[serde(rename = "messages_copy", skip_serializing_if = "Option::is_none")]
    pub messages_copy: Option<String>,
    /// Undo message
    #[serde(rename = "messages_undo", skip_serializing_if = "Option::is_none")]
    pub messages_undo: Option<String>,
    /// Redo message
    #[serde(rename = "messages_redo", skip_serializing_if = "Option::is_none")]
    pub messages_redo: Option<String>,
    /// Toggle code block concealment in messages
    #[serde(rename = "messages_toggle_conceal", skip_serializing_if = "Option::is_none")]
    pub messages_toggle_conceal: Option<String>,
    /// List available models
    #[serde(rename = "model_list", skip_serializing_if = "Option::is_none")]
    pub model_list: Option<String>,
    /// Next recently used model
    #[serde(rename = "model_cycle_recent", skip_serializing_if = "Option::is_none")]
    pub model_cycle_recent: Option<String>,
    /// Previous recently used model
    #[serde(rename = "model_cycle_recent_reverse", skip_serializing_if = "Option::is_none")]
    pub model_cycle_recent_reverse: Option<String>,
    /// List available commands
    #[serde(rename = "command_list", skip_serializing_if = "Option::is_none")]
    pub command_list: Option<String>,
    /// List agents
    #[serde(rename = "agent_list", skip_serializing_if = "Option::is_none")]
    pub agent_list: Option<String>,
    /// Next agent
    #[serde(rename = "agent_cycle", skip_serializing_if = "Option::is_none")]
    pub agent_cycle: Option<String>,
    /// Previous agent
    #[serde(rename = "agent_cycle_reverse", skip_serializing_if = "Option::is_none")]
    pub agent_cycle_reverse: Option<String>,
    /// Clear input field
    #[serde(rename = "input_clear", skip_serializing_if = "Option::is_none")]
    pub input_clear: Option<String>,
    /// Forward delete
    #[serde(rename = "input_forward_delete", skip_serializing_if = "Option::is_none")]
    pub input_forward_delete: Option<String>,
    /// Paste from clipboard
    #[serde(rename = "input_paste", skip_serializing_if = "Option::is_none")]
    pub input_paste: Option<String>,
    /// Submit input
    #[serde(rename = "input_submit", skip_serializing_if = "Option::is_none")]
    pub input_submit: Option<String>,
    /// Insert newline in input
    #[serde(rename = "input_newline", skip_serializing_if = "Option::is_none")]
    pub input_newline: Option<String>,
    /// Previous history item
    #[serde(rename = "history_previous", skip_serializing_if = "Option::is_none")]
    pub history_previous: Option<String>,
    /// Next history item
    #[serde(rename = "history_next", skip_serializing_if = "Option::is_none")]
    pub history_next: Option<String>,
    /// Next child session
    #[serde(rename = "session_child_cycle", skip_serializing_if = "Option::is_none")]
    pub session_child_cycle: Option<String>,
    /// Previous child session
    #[serde(rename = "session_child_cycle_reverse", skip_serializing_if = "Option::is_none")]
    pub session_child_cycle_reverse: Option<String>,
}

impl KeybindsConfig {
    /// Custom keybind configurations
    pub fn new() -> KeybindsConfig {
        KeybindsConfig {
            leader: None,
            app_exit: None,
            editor_open: None,
            theme_list: None,
            sidebar_toggle: None,
            status_view: None,
            session_export: None,
            session_new: None,
            session_list: None,
            session_timeline: None,
            session_share: None,
            session_unshare: None,
            session_interrupt: None,
            session_compact: None,
            messages_page_up: None,
            messages_page_down: None,
            messages_half_page_up: None,
            messages_half_page_down: None,
            messages_first: None,
            messages_last: None,
            messages_copy: None,
            messages_undo: None,
            messages_redo: None,
            messages_toggle_conceal: None,
            model_list: None,
            model_cycle_recent: None,
            model_cycle_recent_reverse: None,
            command_list: None,
            agent_list: None,
            agent_cycle: None,
            agent_cycle_reverse: None,
            input_clear: None,
            input_forward_delete: None,
            input_paste: None,
            input_submit: None,
            input_newline: None,
            history_previous: None,
            history_next: None,
            session_child_cycle: None,
            session_child_cycle_reverse: None,
        }
    }
}

