/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Message is a union (assistant/user). Preserve raw payload to tolerate schema drift.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Message(pub serde_json::Value);

impl Message {
    pub fn new(value: serde_json::Value) -> Message {
        Message(value)
    }
}
