/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Part is a union of many schemas (text/file/tool/etc). Keep raw payload to avoid loss on new variants.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Part(pub serde_json::Value);

impl Part {
    pub fn new(value: serde_json::Value) -> Part {
        Part(value)
    }
}
