/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Path {
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "config")]
    pub config: String,
    #[serde(rename = "worktree")]
    pub worktree: String,
    #[serde(rename = "directory")]
    pub directory: String,
}

impl Path {
    pub fn new(state: String, config: String, worktree: String, directory: String) -> Path {
        Path {
            state,
            config,
            worktree,
            directory,
        }
    }
}

