/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionTime {
    #[serde(rename = "created", default, skip_serializing_if = "Option::is_none")]
    pub created: Option<f64>,
}

impl PermissionTime {
    pub fn new(created: Option<f64>) -> PermissionTime {
        PermissionTime {
            created,
        }
    }
}
