/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSessionIdPermissionsPermissionIdRequest {
    #[serde(rename = "response")]
    pub response: Response,
}

impl PostSessionIdPermissionsPermissionIdRequest {
    pub fn new(response: Response) -> PostSessionIdPermissionsPermissionIdRequest {
        PostSessionIdPermissionsPermissionIdRequest {
            response,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Response {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for Response {
    fn default() -> Response {
        Self::Once
    }
}

