/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Provider {
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "env")]
    pub env: Vec<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "npm", skip_serializing_if = "Option::is_none")]
    pub npm: Option<String>,
    #[serde(rename = "models")]
    pub models: std::collections::HashMap<String, models::Model>,
}

impl Provider {
    pub fn new(name: String, env: Vec<String>, id: String, models: std::collections::HashMap<String, models::Model>) -> Provider {
        Provider {
            api: None,
            name,
            env,
            id,
            npm: None,
            models,
        }
    }
}

