/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTime {
    #[serde(rename = "created", default, skip_serializing_if = "Option::is_none")]
    pub created: Option<f64>,
    #[serde(rename = "updated", default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<f64>,
    #[serde(rename = "compacting", skip_serializing_if = "Option::is_none")]
    pub compacting: Option<f64>,
}

impl SessionTime {
    pub fn new(created: Option<f64>, updated: Option<f64>) -> SessionTime {
        SessionTime {
            created,
            updated,
            compacting: None,
        }
    }
}
