/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolState {
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "input", default, skip_serializing_if = "Option::is_none")]
    pub input: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "raw", default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(rename = "title", default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "time", default, skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::ToolStateErrorTime>>,
    #[serde(rename = "output", default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::FilePart>>,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ToolState {
    pub fn new(status: Option<Status>, input: Option<std::collections::HashMap<String, serde_json::Value>>, raw: Option<String>, title: Option<String>, metadata: Option<std::collections::HashMap<String, serde_json::Value>>, time: Option<models::ToolStateErrorTime>, output: Option<String>, error: Option<String>) -> ToolState {
        ToolState {
            status,
            input,
            raw,
            title,
            metadata,
            time: time.map(Box::new),
            output,
            attachments: None,
            error,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "completed")]
    Completed,
    #[serde(other)]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}
