/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMessage {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "time")]
    pub time: Box<models::PermissionTime>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::UserMessageSummary>>,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "model")]
    pub model: Box<models::SessionSummarizeRequest>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<std::collections::HashMap<String, bool>>,
}

impl UserMessage {
    pub fn new(id: String, session_id: String, role: Role, time: models::PermissionTime, agent: String, model: models::SessionSummarizeRequest) -> UserMessage {
        UserMessage {
            id,
            session_id,
            role,
            time: Box::new(time),
            summary: None,
            agent,
            model: Box::new(model),
            system: None,
            tools: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "user")]
    User,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}

